function stopWatch(){
    let count = 0;
    return function(){
       count++;
       return count;

    }
}

const watch = stopWatch();
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());

const watch1 = stopWatch();
console.log(watch1());
console.log(watch1());
console.log(watch1());
console.log(watch1());
console.log(watch1());
console.log(watch1());
console.log(watch1());
console.log(watch1());
console.log(watch());
console.log(watch());
console.log(watch());

const watch3 = stopWatch();
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch3());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());
console.log(watch());


